name: Bump Version and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: bump_version
        uses: phips28/gh-action-bump-version@v10.1.1
        with:
          tag-prefix: "v"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show new version
        run: echo "New version is ${{ steps.bump_version.outputs.newTag }}"